basicdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djangoBlogApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from home import views

handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

urlpatterns = [
    path('administration/', admin.site.urls),
    path('', views.home, name='home'),
    path('registration/', include('registration.urls', namespace='registration')),
    path('', include('home.urls', namespace='home')),    
    path('ckeditor/', include('ckeditor_uploader.urls'))
]



if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('advertisement/', views.advertisement, name='advertisement'),
    path('join/', views.join, name='join'),
    path('privacy/', views.privacy, name='privacy'),
    path('<str:category>/', views.posts, name='posts'),
    path('posts/<slug:slug>/', views.details, name='details'), 
    path('hitcount/', include('hitcount.urls', 'hitcount')),  
    path('test/<slug:slug>/', views.test, name='test'), 
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Blog App by Rajan Gyawali</title>

		<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:700%7CNunito:300,600" rel="stylesheet"> 

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href={% static 'css/bootstrap.min.css' %}/>

		<!-- Font Awesome Icon -->
		<link type="text/css" rel="stylesheet" href={% static 'css/font-awesome.min.css' %}>

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href={% static 'css/style.css' %}/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
	<body>
		<div id="fb-root"></div>
		<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v7.0"></script>

		<!-- Header -->
		<header id="header">
			<!-- Nav -->
			<div id="nav">
				<!-- Main Nav -->
				<div id="nav-fixed">
					<div class="container">
						<!-- logo -->
						<div class="nav-logo">
							<a href="{% url 'home'%}" class="logo"><img src="{% static 'img/logo.svg' %}" alt=""></a>
						</div>
						<!-- /logo -->

						<!-- nav -->
						<ul class="nav-menu nav navbar-nav">
							<li><a href="{% url 'home:posts' 'posts'  %}">News</a></li>
							<li><a href="{% url 'home:posts' 'popular'  %}">Popular</a></li>
							<li class="cat-1"><a href="{% url 'home:posts' 'Technology' %}">Technology</a></li>
							<li class="cat-2"><a href="{% url 'home:posts' 'Politics' %}">Politics</a></li>
							<li class="cat-3"><a href="{% url 'home:posts' 'Society' %}">Society</a></li>
							<li class="cat-4"><a href="{% url 'home:posts' 'International' %}">International</a></li>
							<li class="cat-2"><a href="{% url 'home:posts' 'Entertainment' %}">Entertainment</a></li>
						</ul>
						<!-- /nav -->

						<!-- search & aside toggle -->
						<div class="nav-btns">
							<button class="aside-btn"><i class="fa fa-bars"></i></button>
							<button class="search-btn"><i class="fa fa-search"></i></button>
							<form action="{% url 'home:posts' 'search' %}" method="GET">
							<div class="search-form">
								<input class="search-input" type="text" name="q" placeholder="Enter Your Search ...">
								<button class="search-close"><i class="fa fa-times"></i></button>
							</div>
							</form>
						</div>
						<!-- /search & aside toggle -->
					</div>
				</div>
				<!-- /Main Nav -->

				<!-- Aside Nav -->
				<div id="nav-aside">
					<!-- nav -->
					<div class="section-row">
						<ul class="nav-aside-menu">
							<li><a href="{% url 'home'%}">Home</a></li>
							<li><a href="{% url 'home:about'%}">About Us</a></li>
							<li><a href="{% url 'home:join'%}">Join Us</a></li>
							<li><a href="{% url 'home:advertisement'%}">Advertisement</a></li>
							<li><a href="{% url 'home:contact'%}">Contacts</a></li>
						</ul>
					</div>
					<!-- /nav -->

					<!-- nav -->
					<div class="section-row">
						<ul class="nav-aside-menu">
							<li><a href="{% url 'home:posts' 'Technology' %}">Technology</a></li>
							<li><a href="{% url 'home:posts' 'Politics' %}">Politics</a></li>
							<li><a href="{% url 'home:posts' 'Society' %}">Society</a></li>
							<li><a href="{% url 'home:posts' 'International' %}">International</a></li>
							<li><a href="{% url 'home:posts' 'Entertainment' %}">Entertainment</a></li>
						</ul>
					</div>
					<!-- /nav -->

					<!-- social links -->
					<div class="section-row">
						<h4>Follow us</h4>
						<ul class="nav-aside-social">
							<li><a href="https://www.facebook.com/sharer/sharer.php?u=http://127.0.0.1:8000/"><i class="fa fa-facebook"></i></a></li>
							<li><a href="https://twitter.com/home?status=Blog%20App%20by%20NT%20Python%20Teamhttp://127.0.0.1:8000/"><i class="fa fa-twitter"></i></a></li>
							<li><a href="https://plus.google.com/share?url=http://127.0.0.1:8000/"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="https://www.linkedin.com/shareArticle?mini=true&url=http://127.0.0.1:8000/"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
					<!-- /social links -->

					<!-- aside nav close -->
					<button class="nav-aside-close"><i class="fa fa-times"></i></button>
					<!-- /aside nav close -->
					<div class="nav-logo">
						<a href="{% url 'home'%}" class="logo"><img src="{% static 'img/logo-footer.svg' %}" alt=""></a>
					</div>
				</div>
				<!-- Aside Nav -->
			</div>
			<!-- /Nav -->
		</header>
		<!-- /Header -->

		{% block section %}
		
		{% endblock section %}
		

		<!-- Footer -->
		<footer id="footer">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-5">
						<div class="footer-widget">
							<div class="footer-logo">
								<a href="{% url 'home'%}" class="logo"><img src="{% static 'img/logo-footer.svg'%}" alt=""></a>
							</div>
							<ul class="footer-nav">
								<li><a href="{% url 'home:privacy'%}">Privacy Policy</a></li>
								<li><a href="{% url 'home:advertisement'%}">Advertisement</a></li>
							</ul>
							<div class="footer-copyright">
								<span>
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved <i class="fa fa-heart-o" aria-hidden="true"></i> by Rajan Gyawali</a>
								</span>
							</div>
						</div>
					</div>

					<div class="col-md-4">
						<div class="row">
							<div class="col-md-12">
								<div class="footer-widget">
									<h3 class="footer-title">About Us</h3>
									<ul class="footer-links">
										<li><a href="{% url 'home:about'%}">About Us</a></li>
										<li><a href="{% url 'home:join'%}">Join Us</a></li>
										<li><a href="{% url 'home:contact'%}">Contacts</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-3">
						<div class="footer-widget">
							<h3 class="footer-title">Join our Newsletter</h3>
							<div class="footer-newsletter">
								<form action={% url 'home' %} method="POST">
								{% csrf_token %}
									<input class="input" type="email" name="subscriber" placeholder="Enter your email">
									<button class="newsletter-btn"><i class="fa fa-paper-plane"></i></button>
								</form>
							</div>
							<ul class="footer-social">
								<li><a href="https://www.facebook.com/sharer/sharer.php?u=http://127.0.0.1:8000/"><i class="fa fa-facebook"></i></a></li>
								<li><a href="https://twitter.com/home?status=Blog%20App%20by%20NT%20Python%20Teamhttp://127.0.0.1:8000/"><i class="fa fa-twitter"></i></a></li>
								<li><a href="https://plus.google.com/share?url=http://127.0.0.1:8000/"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="https://www.linkedin.com/shareArticle?mini=true&url=http://127.0.0.1:8000/"><i class="fa fa-linkedin"></i></a></li>
							</ul>
						</div>
					</div>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</footer>
		<!-- /Footer -->

		<!-- jQuery Plugins -->
		<script src={% static 'js/jquery.min.js' %}></script>
		<script src={% static 'js/bootstrap.min.js' %}></script>
		<script src={% static 'js/main.js' %}></script>

	</body>
</html>